### ISSUE TITLE
Release ToDo

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/profileAAR#10]
- [x] z_trans.append(coord_proc[i][2] + center_y - mean(z_coord_proc))
-> z_trans.append(coord_proc[i][2])

- [x] distance implementieren und als spalte an den export fügen

- [x] beim Import weitere Spalte mit "verwenden" (optional)
-> Wenn x vorhanden, dann zur berechnung des BKS verwenden, sonst nicht

- [x] Zwei Durchläufe, erster Test mit allen fehlern (dann abbrechen) zweiter zum berechnen

- [x] Korrektur des Artikels

- [x] Korrektur der Hilfe

- [x] Export Profilline
